services:
  goro:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ..:/app
      - ../data:/app/data
      - goro-go-build-cache:/root/.cache/go-build
      - goro-go-mod-cache:/go/pkg/mod
    ports:
      - "8080:8080"
    environment:
      - S3_ENDPOINT=http://minio:9000
      - SECURE_LINK_SECRET=change-me-in-production

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
    environment:
      - SECURE_LINK_SECRET=change-me-in-production

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio_data:/data

volumes:
  goro-go-build-cache:
  goro-go-mod-cache:
  minio_data: